# Generated by Django 5.2.14 on 2026-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Identifier from the upstream book API (e.g. Open Library author key).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('isbn_10', models.CharField(blank=True, db_index=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, db_index=True, max_length=13)),
                ('description', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField(blank=True, help_text='Publication date; day/month may be approximate for older titles.', null=True)),
                ('language', models.CharField(blank=True, default='en', help_text="IETF language tag, e.g. 'en', 'es'.", max_length=10)),
                ('cover_image_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Identifier from the upstream book API (e.g. Open Library work key).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='catalog.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
