/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["root_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/apple/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/apple/
         *     Verify an Apple identity token issued by Sign in with Apple (web JS SDK or
         *     native iOS/macOS SDK).
         *
         *     Body:
         *       {
         *         "identity_token": "<JWT from Apple>",
         *         "first_name": "...",   // optional — Apple only sends this on first auth
         *         "last_name":  "..."    // optional
         *       }
         */
        post: operations["auth_apple_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/child-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/auth/child-accounts/  — list child user accounts under this parent
         *     POST /api/auth/child-accounts/  — parent creates a full account for a child (13+)
         */
        get: operations["auth_child_accounts_list"];
        put?: never;
        /**
         * @description GET  /api/auth/child-accounts/  — list child user accounts under this parent
         *     POST /api/auth/child-accounts/  — parent creates a full account for a child (13+)
         */
        post: operations["auth_child_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/child-profiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/auth/child-profiles/  — list this parent's child profiles
         *     POST /api/auth/child-profiles/  — create a new child profile
         */
        get: operations["auth_child_profiles_list"];
        put?: never;
        /**
         * @description GET  /api/auth/child-profiles/  — list this parent's child profiles
         *     POST /api/auth/child-profiles/  — create a new child profile
         */
        post: operations["auth_child_profiles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/child-profiles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PUT/PATCH/DELETE /api/auth/child-profiles/<pk>/ */
        get: operations["auth_child_profiles_retrieve"];
        /** @description GET/PUT/PATCH/DELETE /api/auth/child-profiles/<pk>/ */
        put: operations["auth_child_profiles_update"];
        post?: never;
        /** @description GET/PUT/PATCH/DELETE /api/auth/child-profiles/<pk>/ */
        delete: operations["auth_child_profiles_destroy"];
        options?: never;
        head?: never;
        /** @description GET/PUT/PATCH/DELETE /api/auth/child-profiles/<pk>/ */
        patch: operations["auth_child_profiles_partial_update"];
        trace?: never;
    };
    "/api/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/google/
         *     Verify a Google ID token issued by the Google Sign-In SDK (web or native).
         *     Body: { "id_token": "<token from Google>" }
         */
        post: operations["auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/login/ — authenticate with email+password, receive JWT. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/logout/ — blacklist the refresh token and clear cookies. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/auth/me/ — return the authenticated user's profile. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/register/ — create a parent account with email+password. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/token/refresh/
         *     Accept the refresh token from the request body (native apps) or from the
         *     HttpOnly cookie (browsers).  Returns a new access token (and rotated refresh
         *     token when ROTATE_REFRESH_TOKENS=True).
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChildProfile: {
            readonly id: number;
            name: string;
            /** Format: uri */
            avatar_url?: string;
            /** Format: date */
            date_of_birth?: string | null;
            pin?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Used by a parent to create a full child user account (age 13+). */
        CreateChildAccount: {
            /**
             * Email address
             * Format: email
             */
            email?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            password?: string;
            /** Format: date */
            date_of_birth?: string | null;
        };
        PatchedChildProfile: {
            readonly id?: number;
            name?: string;
            /** Format: uri */
            avatar_url?: string;
            /** Format: date */
            date_of_birth?: string | null;
            pin?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_apple_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_child_accounts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateChildAccount"][];
                };
            };
        };
    };
    auth_child_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChildAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateChildAccount"];
                "multipart/form-data": components["schemas"]["CreateChildAccount"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateChildAccount"];
                };
            };
        };
    };
    auth_child_profiles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildProfile"][];
                };
            };
        };
    };
    auth_child_profiles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["ChildProfile"];
                "multipart/form-data": components["schemas"]["ChildProfile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildProfile"];
                };
            };
        };
    };
    auth_child_profiles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildProfile"];
                };
            };
        };
    };
    auth_child_profiles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["ChildProfile"];
                "multipart/form-data": components["schemas"]["ChildProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildProfile"];
                };
            };
        };
    };
    auth_child_profiles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_child_profiles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChildProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChildProfile"];
                "multipart/form-data": components["schemas"]["PatchedChildProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildProfile"];
                };
            };
        };
    };
    auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
